<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Grammar"
    nsURI="http://gts.inf.um.es/gra2mol-examples/Grammar" nsPrefix="ANTLRGrammar">
  <eClassifiers xsi:type="ecore:EClass" name="GrammarGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="grammarDefs" upperBound="-1"
        eType="#//GrammarDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GrammarDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//Rule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="derivations" upperBound="-1"
        eType="#//Rule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LexicalRule" eSuperTypes="#//Rule"/>
  <eClassifiers xsi:type="ecore:EClass" name="SintacticRule" eSuperTypes="#//Rule"/>
</ecore:EPackage>
