<?xml version="1.0" encoding="UTF-8"?>
<CST:Node xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:CST="http://gts.inf.um.es/modernization/cst" kind="CST">
  <children xsi:type="CST:Node" kind="file">
    <children xsi:type="CST:Leaf" kind="path" value="/home/jcanovas/eclipses/eclipse-indigo/workspace/Grammar2Model.examples.skeleton/files/src/scripts/example1"/>
    <children xsi:type="CST:Leaf" kind="filename" value="example1"/>
    <children xsi:type="CST:Node" kind="mainRule">
      <children xsi:type="CST:Node" kind="statement">
        <children xsi:type="CST:Node" kind="print_statement">
          <children xsi:type="CST:Leaf" kind="TOKEN" value="print" line="1"/>
          <children xsi:type="CST:Leaf" kind="DQVAL" value="&quot;Hello, World!&quot;"
              pos="6" line="1"/>
        </children>
      </children>
    </children>
  </children>
  <children xsi:type="CST:Node" kind="file">
    <children xsi:type="CST:Leaf" kind="path" value="/home/jcanovas/eclipses/eclipse-indigo/workspace/Grammar2Model.examples.skeleton/files/src/scripts/example2"/>
    <children xsi:type="CST:Leaf" kind="filename" value="example2"/>
    <children xsi:type="CST:Node" kind="mainRule">
      <children xsi:type="CST:Node" kind="statement">
        <children xsi:type="CST:Node" kind="print_statement">
          <children xsi:type="CST:Leaf" kind="TOKEN" value="print" line="1"/>
          <children xsi:type="CST:Leaf" kind="DQVAL" value="&quot;Hello again!&quot;"
              pos="6" line="1"/>
        </children>
      </children>
    </children>
  </children>
</CST:Node>
