<kdm:Segment xmlns:code='http://www.eclipse.org/MoDisco/kdm/code' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation='http://www.eclipse.org/MoDisco/kdm/source files/metamodels/kdm.ecore#//source http://www.eclipse.org/MoDisco/kdm/action files/metamodels/kdm.ecore#//action http://www.eclipse.org/MoDisco/kdm/kdm files/metamodels/kdm.ecore#//kdm http://www.eclipse.org/MoDisco/kdm/code files/metamodels/kdm.ecore#//code' xmlns:action='http://www.eclipse.org/MoDisco/kdm/action' xmi:version='2.0' xmlns:xmi='http://www.omg.org/XMI' xmlns:kdm='http://www.eclipse.org/MoDisco/kdm/kdm' xmlns:source='http://www.eclipse.org/MoDisco/kdm/source'>
<model name='Platform Code Model (Struts)' xsi:type='code:CodeModel'>
<codeElement name='Java Datatypes' xsi:type='code:LanguageUnit'>
<codeElement xsi:type='code:BooleanType'/>
<codeElement xsi:type='code:StringType'/>
</codeElement>
<codeElement xsi:type='code:CompilationUnit'>
<codeElement name='HttpServletRequest' xsi:type='code:ClassUnit'>
<codeElement name='getSession' kind='method' xsi:type='code:MethodUnit' export='public'/>
</codeElement>
</codeElement>
<codeElement xsi:type='code:CompilationUnit'>
<codeElement name='HttpSession' xsi:type='code:ClassUnit'>
<codeElement name='setAttribute' kind='method' xsi:type='code:MethodUnit' export='public'/>
<codeElement name='getAttribute' kind='method' xsi:type='code:MethodUnit' export='public'/>
</codeElement>
</codeElement>
<codeElement xsi:type='code:CompilationUnit'>
<codeElement name='ActionForward' xsi:type='code:ClassUnit'/>
</codeElement>
</model>
<model name='CodeModel' xsi:type='code:CodeModel'>
<codeElement xsi:type='code:CompilationUnit'>
<codeElement name='ActionVerNoticia' xsi:type='code:ClassUnit'>
<codeElement name='execute' kind='method' xsi:type='code:MethodUnit' export='public'>
<codeElement xsi:type='code:Signature'>
<parameterUnit name='actionMapping' kind='byValue' xsi:type='code:ParameterUnit'/>
<parameterUnit name='actionForm' kind='byValue' xsi:type='code:ParameterUnit'/>
<parameterUnit name='request' kind='byValue' xsi:type='code:ParameterUnit'/>
<parameterUnit name='response' kind='byValue' xsi:type='code:ParameterUnit'/>
<parameterUnit kind='return' type='#//@model.0/@codeElement.3/@codeElement.0' xsi:type='code:ParameterUnit'/>
</codeElement>
<codeElement from='#//@model.1/@codeElement.0/@codeElement.0/@codeElement.0' xsi:type='action:EntryFlow' to='#//@model.1/@codeElement.0/@codeElement.0/@codeElement.0/@codeElement.2'/>
<codeElement name='variableDeclaration' kind='declaration' xsi:type='action:ActionElement'>
<codeElement name='bean' kind='global' xsi:type='code:StorableUnit'/>
<codeElement from='#//@model.1/@codeElement.0/@codeElement.0/@codeElement.0/@codeElement.2' xsi:type='action:Writes' to='#//@model.1/@codeElement.0/@codeElement.0/@codeElement.0/@codeElement.2/@codeElement.0'/>
<codeElement name='CastExpression' xsi:type='action:ActionElement'/>
</codeElement>
<codeElement name='variableDeclaration' kind='declaration' xsi:type='action:ActionElement'>
<codeElement name='noticia' kind='global' xsi:type='code:StorableUnit'/>
<codeElement from='#//@model.1/@codeElement.0/@codeElement.0/@codeElement.0/@codeElement.3' xsi:type='action:Writes' to='#//@model.1/@codeElement.0/@codeElement.0/@codeElement.0/@codeElement.3/@codeElement.0'/>
<codeElement name='FunctionCall' xsi:type='action:ActionElement'>
<codeElement from='#//@model.1/@codeElement.0/@codeElement.0/@codeElement.0/@codeElement.3/@codeElement.2' xsi:type='action:Calls' to='#//@model.0/@codeElement.1/@codeElement.0/@codeElement.0'/>
<codeElement from='#//@model.1/@codeElement.0/@codeElement.0/@codeElement.0/@codeElement.3/@codeElement.2' xsi:type='action:Calls' to='#//@model.0/@codeElement.2/@codeElement.0/@codeElement.0'/>
</codeElement>
</codeElement>
<codeElement name='expression' kind='expression' xsi:type='action:ActionElement'>
<codeElement name='FunctionCall' xsi:type='action:ActionElement'>
<codeElement from='#//@model.1/@codeElement.0/@codeElement.0/@codeElement.0/@codeElement.4/@codeElement.0' xsi:type='action:Reads' to='#//@model.1/@codeElement.0/@codeElement.0/@codeElement.0/@codeElement.2/@codeElement.0'/>
<codeElement from='#//@model.1/@codeElement.0/@codeElement.0/@codeElement.0/@codeElement.4/@codeElement.0' xsi:type='action:Calls' to='#//@model.0/@codeElement.1/@codeElement.0/@codeElement.0'/>
</codeElement>
</codeElement>
<codeElement name='expression' kind='expression' xsi:type='action:ActionElement'>
<codeElement name='FunctionCall' xsi:type='action:ActionElement'>
<codeElement from='#//@model.1/@codeElement.0/@codeElement.0/@codeElement.0/@codeElement.5/@codeElement.0' xsi:type='action:Reads' to='#//@model.1/@codeElement.0/@codeElement.0/@codeElement.0/@codeElement.2/@codeElement.0'/>
<codeElement from='#//@model.1/@codeElement.0/@codeElement.0/@codeElement.0/@codeElement.5/@codeElement.0' xsi:type='action:Calls' to='#//@model.0/@codeElement.1/@codeElement.0/@codeElement.0'/>
</codeElement>
</codeElement>
<codeElement name='expression' kind='expression' xsi:type='action:ActionElement'>
<codeElement name='FunctionCall' xsi:type='action:ActionElement'>
<codeElement from='#//@model.1/@codeElement.0/@codeElement.0/@codeElement.0/@codeElement.6/@codeElement.0' xsi:type='action:Reads' to='#//@model.1/@codeElement.0/@codeElement.0/@codeElement.0/@codeElement.2/@codeElement.0'/>
<codeElement from='#//@model.1/@codeElement.0/@codeElement.0/@codeElement.0/@codeElement.6/@codeElement.0' xsi:type='action:Calls' to='#//@model.0/@codeElement.1/@codeElement.0/@codeElement.0'/>
</codeElement>
</codeElement>
<codeElement name='expression' kind='expression' xsi:type='action:ActionElement'>
<codeElement name='FunctionCall' xsi:type='action:ActionElement'>
<codeElement from='#//@model.1/@codeElement.0/@codeElement.0/@codeElement.0/@codeElement.7/@codeElement.0' xsi:type='action:Reads' to='#//@model.1/@codeElement.0/@codeElement.0/@codeElement.0/@codeElement.0/@parameterUnit.2'/>
<codeElement from='#//@model.1/@codeElement.0/@codeElement.0/@codeElement.0/@codeElement.7/@codeElement.0' xsi:type='action:Calls' to='#//@model.0/@codeElement.1/@codeElement.0/@codeElement.0'/>
</codeElement>
</codeElement>
<codeElement name='return' kind='return' xsi:type='action:ActionElement'/>
</codeElement>
</codeElement>
</codeElement>
<codeElement xsi:type='code:CompilationUnit'>
<codeElement name='ActionLogin' xsi:type='code:ClassUnit'>
<codeElement name='execute' kind='method' xsi:type='code:MethodUnit' export='public'>
<codeElement xsi:type='code:Signature'>
<parameterUnit name='actionMapping' kind='byValue' xsi:type='code:ParameterUnit'/>
<parameterUnit name='actionForm' kind='byValue' xsi:type='code:ParameterUnit'/>
<parameterUnit name='request' kind='byValue' xsi:type='code:ParameterUnit'/>
<parameterUnit name='response' kind='byValue' xsi:type='code:ParameterUnit'/>
<parameterUnit kind='return' type='#//@model.0/@codeElement.3/@codeElement.0' xsi:type='code:ParameterUnit'/>
</codeElement>
<codeElement from='#//@model.1/@codeElement.1/@codeElement.0/@codeElement.0' xsi:type='action:EntryFlow' to='#//@model.1/@codeElement.1/@codeElement.0/@codeElement.0/@codeElement.2'/>
<codeElement name='variableDeclaration' kind='declaration' xsi:type='action:ActionElement'>
<codeElement name='bean' kind='global' xsi:type='code:StorableUnit'/>
<codeElement from='#//@model.1/@codeElement.1/@codeElement.0/@codeElement.0/@codeElement.2' xsi:type='action:Writes' to='#//@model.1/@codeElement.1/@codeElement.0/@codeElement.0/@codeElement.2/@codeElement.0'/>
<codeElement name='CastExpression' xsi:type='action:ActionElement'/>
</codeElement>
<codeElement name='if' kind='if' xsi:type='action:ActionElement'>
<codeElement from='#//@model.1/@codeElement.1/@codeElement.0/@codeElement.0/@codeElement.3' xsi:type='action:FalseFlow' to='#//@model.1/@codeElement.1/@codeElement.0/@codeElement.0/@codeElement.3/@codeElement.1'/>
<codeElement name='falseFlow' kind='falseFlow' xsi:type='action:ActionElement'/>
<codeElement from='#//@model.1/@codeElement.1/@codeElement.0/@codeElement.0/@codeElement.3' xsi:type='action:TrueFlow' to='#//@model.1/@codeElement.1/@codeElement.0/@codeElement.0/@codeElement.3/@codeElement.3'/>
<codeElement name='trueFlow' kind='trueFlow' xsi:type='action:ActionElement'>
<codeElement kind='block' xsi:type='action:ActionElement'>
<codeElement name='expression' kind='expression' xsi:type='action:ActionElement'>
<codeElement name='FunctionCall' xsi:type='action:ActionElement'>
<codeElement from='#//@model.1/@codeElement.1/@codeElement.0/@codeElement.0/@codeElement.3/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.0' xsi:type='action:Calls' to='#//@model.0/@codeElement.1/@codeElement.0/@codeElement.0'/>
<codeElement from='#//@model.1/@codeElement.1/@codeElement.0/@codeElement.0/@codeElement.3/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.0' xsi:type='action:Calls' to='#//@model.0/@codeElement.2/@codeElement.0/@codeElement.0'/>
</codeElement>
</codeElement>
</codeElement>
</codeElement>
</codeElement>
<codeElement name='expression' kind='expression' xsi:type='action:ActionElement'>
<codeElement name='FunctionCall' xsi:type='action:ActionElement'>
<codeElement from='#//@model.1/@codeElement.1/@codeElement.0/@codeElement.0/@codeElement.4/@codeElement.0' xsi:type='action:Reads' to='#//@model.1/@codeElement.1/@codeElement.0/@codeElement.0/@codeElement.0/@parameterUnit.2'/>
<codeElement from='#//@model.1/@codeElement.1/@codeElement.0/@codeElement.0/@codeElement.4/@codeElement.0' xsi:type='action:Calls' to='#//@model.0/@codeElement.1/@codeElement.0/@codeElement.0'/>
<codeElement from='#//@model.1/@codeElement.1/@codeElement.0/@codeElement.0/@codeElement.4/@codeElement.0' xsi:type='action:Calls' to='#//@model.0/@codeElement.2/@codeElement.0/@codeElement.0'/>
</codeElement>
</codeElement>
<codeElement name='if' kind='if' xsi:type='action:ActionElement'>
<codeElement from='#//@model.1/@codeElement.1/@codeElement.0/@codeElement.0/@codeElement.5' xsi:type='action:FalseFlow' to='#//@model.1/@codeElement.1/@codeElement.0/@codeElement.0/@codeElement.5/@codeElement.1'/>
<codeElement name='falseFlow' kind='falseFlow' xsi:type='action:ActionElement'>
<codeElement name='return' kind='return' xsi:type='action:ActionElement'/>
</codeElement>
<codeElement from='#//@model.1/@codeElement.1/@codeElement.0/@codeElement.0/@codeElement.5' xsi:type='action:TrueFlow' to='#//@model.1/@codeElement.1/@codeElement.0/@codeElement.0/@codeElement.5/@codeElement.3'/>
<codeElement name='trueFlow' kind='trueFlow' xsi:type='action:ActionElement'>
<codeElement name='return' kind='return' xsi:type='action:ActionElement'/>
</codeElement>
</codeElement>
</codeElement>
</codeElement>
</codeElement>
<codeElement xsi:type='code:CompilationUnit'>
<codeElement name='BeanTablon' xsi:type='code:ClassUnit'>
<codeElement name='tituloSeleccionado' kind='global' xsi:type='code:StorableUnit'/>
<codeElement name='titulo' kind='global' xsi:type='code:StorableUnit'/>
<codeElement name='contenido' kind='global' xsi:type='code:StorableUnit'/>
<codeElement name='autor' kind='global' xsi:type='code:StorableUnit'/>
<codeElement name='validate' kind='method' xsi:type='code:MethodUnit' export='public'>
<codeElement xsi:type='code:Signature'>
<parameterUnit name='mapping' kind='byValue' xsi:type='code:ParameterUnit'/>
<parameterUnit name='request' kind='byValue' xsi:type='code:ParameterUnit'/>
<parameterUnit kind='return' xsi:type='code:ParameterUnit'/>
</codeElement>
<codeElement from='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.4' xsi:type='action:EntryFlow' to='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.4/@codeElement.2'/>
<codeElement name='variableDeclaration' kind='declaration' xsi:type='action:ActionElement'>
<codeElement name='errores' kind='global' xsi:type='code:StorableUnit'/>
<codeElement from='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.4/@codeElement.2' xsi:type='action:Writes' to='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.4/@codeElement.2/@codeElement.0'/>
</codeElement>
<codeElement name='if' kind='if' xsi:type='action:ActionElement'>
<codeElement from='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.4/@codeElement.3' xsi:type='action:FalseFlow' to='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.4/@codeElement.3/@codeElement.1'/>
<codeElement name='falseFlow' kind='falseFlow' xsi:type='action:ActionElement'/>
<codeElement from='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.4/@codeElement.3' xsi:type='action:TrueFlow' to='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.4/@codeElement.3/@codeElement.3'/>
<codeElement name='trueFlow' kind='trueFlow' xsi:type='action:ActionElement'>
<codeElement name='expression' kind='expression' xsi:type='action:ActionElement'>
<codeElement name='FunctionCall' xsi:type='action:ActionElement'>
<codeElement from='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.4/@codeElement.3/@codeElement.3/@codeElement.0/@codeElement.0' xsi:type='action:Reads' to='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.4/@codeElement.2/@codeElement.0'/>
<codeElement from='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.4/@codeElement.3/@codeElement.3/@codeElement.0/@codeElement.0' xsi:type='action:Calls' to='#//@model.0/@codeElement.1/@codeElement.0/@codeElement.0'/>
</codeElement>
</codeElement>
</codeElement>
</codeElement>
<codeElement name='return' kind='return' xsi:type='action:ActionElement'/>
</codeElement>
<codeElement name='isTituloNoValido' kind='method' xsi:type='code:MethodUnit' export='public'>
<codeElement xsi:type='code:Signature'>
<parameterUnit name='t' kind='byValue' xsi:type='code:ParameterUnit'/>
</codeElement>
<codeElement from='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.5' xsi:type='action:EntryFlow' to='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.5/@codeElement.2'/>
<codeElement name='if' kind='if' xsi:type='action:ActionElement'>
<codeElement from='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.5/@codeElement.2' xsi:type='action:FalseFlow' to='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.5/@codeElement.2/@codeElement.1'/>
<codeElement name='falseFlow' kind='falseFlow' xsi:type='action:ActionElement'/>
<codeElement from='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.5/@codeElement.2' xsi:type='action:TrueFlow' to='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.5/@codeElement.2/@codeElement.3'/>
<codeElement name='trueFlow' kind='trueFlow' xsi:type='action:ActionElement'>
<codeElement name='return' kind='return' xsi:type='action:ActionElement'/>
</codeElement>
</codeElement>
<codeElement name='return' kind='return' xsi:type='action:ActionElement'/>
</codeElement>
<codeElement name='setTituloSeleccionado' kind='method' xsi:type='code:MethodUnit' export='public'>
<codeElement xsi:type='code:Signature'>
<parameterUnit name='tituloSeleccionado' kind='byValue' xsi:type='code:ParameterUnit'/>
</codeElement>
<codeElement from='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.6' xsi:type='action:EntryFlow' to='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.6/@codeElement.2'/>
<codeElement name='expression' kind='expression' xsi:type='action:ActionElement'>
<codeElement name='BinaryExpression' xsi:type='action:ActionElement'/>
</codeElement>
</codeElement>
<codeElement name='getTituloSeleccionado' kind='method' xsi:type='code:MethodUnit' export='public'>
<codeElement xsi:type='code:Signature'>
<parameterUnit kind='return' xsi:type='code:ParameterUnit'/>
</codeElement>
<codeElement from='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.7' xsi:type='action:EntryFlow' to='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.7/@codeElement.2'/>
<codeElement name='return' kind='return' xsi:type='action:ActionElement'/>
</codeElement>
<codeElement name='setTitulo' kind='method' xsi:type='code:MethodUnit' export='public'>
<codeElement xsi:type='code:Signature'>
<parameterUnit name='titulo' kind='byValue' xsi:type='code:ParameterUnit'/>
</codeElement>
<codeElement from='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.8' xsi:type='action:EntryFlow' to='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.8/@codeElement.2'/>
<codeElement name='expression' kind='expression' xsi:type='action:ActionElement'>
<codeElement name='BinaryExpression' xsi:type='action:ActionElement'/>
</codeElement>
</codeElement>
<codeElement name='getTitulo' kind='method' xsi:type='code:MethodUnit' export='public'>
<codeElement xsi:type='code:Signature'>
<parameterUnit kind='return' xsi:type='code:ParameterUnit'/>
</codeElement>
<codeElement from='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.9' xsi:type='action:EntryFlow' to='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.9/@codeElement.2'/>
<codeElement name='return' kind='return' xsi:type='action:ActionElement'/>
</codeElement>
<codeElement name='setContenido' kind='method' xsi:type='code:MethodUnit' export='public'>
<codeElement xsi:type='code:Signature'>
<parameterUnit name='contenido' kind='byValue' xsi:type='code:ParameterUnit'/>
</codeElement>
<codeElement from='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.10' xsi:type='action:EntryFlow' to='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.10/@codeElement.2'/>
<codeElement name='expression' kind='expression' xsi:type='action:ActionElement'>
<codeElement name='BinaryExpression' xsi:type='action:ActionElement'/>
</codeElement>
</codeElement>
<codeElement name='getContenido' kind='method' xsi:type='code:MethodUnit' export='public'>
<codeElement xsi:type='code:Signature'>
<parameterUnit kind='return' xsi:type='code:ParameterUnit'/>
</codeElement>
<codeElement from='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.11' xsi:type='action:EntryFlow' to='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.11/@codeElement.2'/>
<codeElement name='return' kind='return' xsi:type='action:ActionElement'/>
</codeElement>
<codeElement name='setAutor' kind='method' xsi:type='code:MethodUnit' export='public'>
<codeElement xsi:type='code:Signature'>
<parameterUnit name='autor' kind='byValue' xsi:type='code:ParameterUnit'/>
</codeElement>
<codeElement from='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.12' xsi:type='action:EntryFlow' to='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.12/@codeElement.2'/>
<codeElement name='expression' kind='expression' xsi:type='action:ActionElement'>
<codeElement name='BinaryExpression' xsi:type='action:ActionElement'/>
</codeElement>
</codeElement>
<codeElement name='getAutor' kind='method' xsi:type='code:MethodUnit' export='public'>
<codeElement xsi:type='code:Signature'>
<parameterUnit kind='return' xsi:type='code:ParameterUnit'/>
</codeElement>
<codeElement from='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.13' xsi:type='action:EntryFlow' to='#//@model.1/@codeElement.2/@codeElement.0/@codeElement.13/@codeElement.2'/>
<codeElement name='return' kind='return' xsi:type='action:ActionElement'/>
</codeElement>
</codeElement>
</codeElement>
<codeElement xsi:type='code:CompilationUnit'>
<codeElement name='ActionPublicarNoticia' xsi:type='code:ClassUnit'>
<codeElement name='execute' kind='method' xsi:type='code:MethodUnit' export='public'>
<codeElement xsi:type='code:Signature'>
<parameterUnit name='actionMapping' kind='byValue' xsi:type='code:ParameterUnit'/>
<parameterUnit name='actionForm' kind='byValue' xsi:type='code:ParameterUnit'/>
<parameterUnit name='request' kind='byValue' xsi:type='code:ParameterUnit'/>
<parameterUnit name='response' kind='byValue' xsi:type='code:ParameterUnit'/>
<parameterUnit kind='return' type='#//@model.0/@codeElement.3/@codeElement.0' xsi:type='code:ParameterUnit'/>
</codeElement>
<codeElement from='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0' xsi:type='action:EntryFlow' to='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.2'/>
<codeElement name='variableDeclaration' kind='declaration' xsi:type='action:ActionElement'>
<codeElement name='bean' kind='global' xsi:type='code:StorableUnit'/>
<codeElement from='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.2' xsi:type='action:Writes' to='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.2/@codeElement.0'/>
<codeElement name='CastExpression' xsi:type='action:ActionElement'/>
</codeElement>
<codeElement name='if' kind='if' xsi:type='action:ActionElement'>
<codeElement from='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.3' xsi:type='action:FalseFlow' to='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.3/@codeElement.1'/>
<codeElement name='falseFlow' kind='falseFlow' xsi:type='action:ActionElement'/>
<codeElement from='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.3' xsi:type='action:TrueFlow' to='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.3/@codeElement.3'/>
<codeElement name='trueFlow' kind='trueFlow' xsi:type='action:ActionElement'>
<codeElement kind='block' xsi:type='action:ActionElement'>
<codeElement name='expression' kind='expression' xsi:type='action:ActionElement'>
<codeElement name='FunctionCall' xsi:type='action:ActionElement'>
<codeElement from='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.3/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.0' xsi:type='action:Reads' to='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.0/@parameterUnit.2'/>
<codeElement from='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.3/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.0' xsi:type='action:Calls' to='#//@model.0/@codeElement.1/@codeElement.0/@codeElement.0'/>
<codeElement from='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.3/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.0' xsi:type='action:Calls' to='#//@model.0/@codeElement.2/@codeElement.0/@codeElement.0'/>
</codeElement>
</codeElement>
<codeElement name='return' kind='return' xsi:type='action:ActionElement'/>
</codeElement>
</codeElement>
</codeElement>
<codeElement name='variableDeclaration' kind='declaration' xsi:type='action:ActionElement'>
<codeElement name='datos' kind='global' xsi:type='code:StorableUnit'/>
<codeElement from='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.4' xsi:type='action:Writes' to='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.4/@codeElement.0'/>
<codeElement name='CastExpression' xsi:type='action:ActionElement'/>
</codeElement>
<codeElement name='if' kind='if' xsi:type='action:ActionElement'>
<codeElement from='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.5' xsi:type='action:FalseFlow' to='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.5/@codeElement.1'/>
<codeElement name='falseFlow' kind='falseFlow' xsi:type='action:ActionElement'/>
<codeElement from='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.5' xsi:type='action:TrueFlow' to='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.5/@codeElement.3'/>
<codeElement name='trueFlow' kind='trueFlow' xsi:type='action:ActionElement'>
<codeElement kind='block' xsi:type='action:ActionElement'>
<codeElement name='expression' kind='expression' xsi:type='action:ActionElement'>
<codeElement name='BinaryExpression' xsi:type='action:ActionElement'/>
</codeElement>
<codeElement name='expression' kind='expression' xsi:type='action:ActionElement'>
<codeElement name='FunctionCall' xsi:type='action:ActionElement'>
<codeElement from='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.5/@codeElement.3/@codeElement.0/@codeElement.1/@codeElement.0' xsi:type='action:Reads' to='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.0/@parameterUnit.2'/>
<codeElement from='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.5/@codeElement.3/@codeElement.0/@codeElement.1/@codeElement.0' xsi:type='action:Calls' to='#//@model.0/@codeElement.1/@codeElement.0/@codeElement.0'/>
<codeElement from='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.5/@codeElement.3/@codeElement.0/@codeElement.1/@codeElement.0' xsi:type='action:Calls' to='#//@model.0/@codeElement.2/@codeElement.0/@codeElement.0'/>
</codeElement>
</codeElement>
</codeElement>
</codeElement>
</codeElement>
<codeElement name='expression' kind='expression' xsi:type='action:ActionElement'>
<codeElement name='FunctionCall' xsi:type='action:ActionElement'>
<codeElement from='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.6/@codeElement.0' xsi:type='action:Calls' to='#//@model.0/@codeElement.1/@codeElement.0/@codeElement.0'/>
<codeElement from='#//@model.1/@codeElement.3/@codeElement.0/@codeElement.0/@codeElement.6/@codeElement.0' xsi:type='action:Calls' to='#//@model.0/@codeElement.2/@codeElement.0/@codeElement.0'/>
</codeElement>
</codeElement>
<codeElement name='return' kind='return' xsi:type='action:ActionElement'/>
</codeElement>
</codeElement>
</codeElement>
</model>
<model xsi:type='source:InventoryModel'>
<inventoryElement name='StrutsApplication' xsi:type='source:Project'>
<inventoryElement name='src' xsi:type='source:Directory' path='/'>
<inventoryElement name='ActionVerNoticia' xsi:type='source:SourceFile'/>
<inventoryElement name='ActionLogin' xsi:type='source:SourceFile'/>
<inventoryElement name='BeanTablon' xsi:type='source:SourceFile'/>
<inventoryElement name='ActionPublicarNoticia' xsi:type='source:SourceFile'/>
</inventoryElement>
</inventoryElement>
</model>
</kdm:Segment>