<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mmaemilia"
    nsURI="file://C:/Users/martina/Desktop/eclipse_indigo/workspace/textToModelTrasformation/skipRulesExample/metamodels/mmAEmilia.ecore"
    nsPrefix="mmaemilia">
  <eClassifiers xsi:type="ecore:EClass" name="AEmiliaSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="archiTypeDecl" lowerBound="1"
        eType="#//ArchiType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchiType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aetDeclaration" lowerBound="1"
        eType="#//ArchiElemTypes" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atDeclaration" lowerBound="1"
        eType="#//ArchiTopology" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="atName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="header" lowerBound="1"
        eType="#//Headers/AT_Header" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchiElemTypes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="etDeclaration" lowerBound="1"
        upperBound="-1" eType="#//ElemType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchiTopology">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aeiDecl" upperBound="-1"
        eType="#//ArchiElemInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attDecl" upperBound="-1"
        eType="#//Attachement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interaction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="throughput" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="utilization" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalInteraction" eSuperTypes="#//Interaction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//InteractionType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitecturalInteraction" eSuperTypes="#//Interaction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Is_A" lowerBound="1" eType="#//LocalInteraction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputInteraction" eSuperTypes="#//LocalInteraction"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutputInteraction" eSuperTypes="#//LocalInteraction"/>
  <eClassifiers xsi:type="ecore:EEnum" name="InteractionType">
    <eLiterals name="UNI"/>
    <eLiterals name="AND" value="1"/>
    <eLiterals name="OR" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchiElemInstance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actualParam" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TypeOf" lowerBound="1"
        eType="#//ElemType" eKeys="#//ElemType/etName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aiDecl" upperBound="-1"
        eType="#//ArchitecturalInteraction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="is_local_I" upperBound="-1"
        eType="#//localInput" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="is_local_O" upperBound="-1"
        eType="#//localOutput" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="throughput" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="utilization" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attachement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" eType="#//To"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" lowerBound="1" eType="#//From"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElemType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="iiDecl" upperBound="-1"
        eType="#//InputInteraction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oiDecl" upperBound="-1"
        eType="#//OutputInteraction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="etName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elemHeader" lowerBound="1"
        eType="#//Headers/ET_Header" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviorDecl" lowerBound="1"
        eType="#//Behavior/Behavior" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="To">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TO" lowerBound="1" eType="#//ArchiElemInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="a" lowerBound="1" eType="#//localInput"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="From">
    <eStructuralFeatures xsi:type="ecore:EReference" name="FROM" lowerBound="1" eType="#//ArchiElemInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="da" lowerBound="1" eType="#//localOutput"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="localInput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="is_input" lowerBound="1"
        eType="#//InputInteraction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="localOutput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="is_output" lowerBound="1"
        eType="#//OutputInteraction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="DataType" nsURI="file://C:/Users/martina/Desktop/eclipse_indigo/workspace/textToModelTrasformation/skipRulesExample/metamodels/mmAEmilia.ecore#//DataType"
      nsPrefix="DataType">
    <eClassifiers xsi:type="ecore:EClass" name="DataType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Normal" eSuperTypes="#//DataType/DataType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Special" eSuperTypes="#//DataType/DataType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#//DataType/SpecialType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SpecialType">
      <eLiterals name="prio" literal="prio"/>
      <eLiterals name="rate" value="1" literal="rate"/>
      <eLiterals name="weight" value="2" literal="weight"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Integer" eSuperTypes="#//DataType/Normal"/>
    <eClassifiers xsi:type="ecore:EClass" name="Record" eSuperTypes="#//DataType/Normal">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="field_decl_seq" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Array" eSuperTypes="#//DataType/Normal">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lenght" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="elemType" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="List" eSuperTypes="#//DataType/Normal">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementType" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//DataType/Normal"/>
    <eClassifiers xsi:type="ecore:EClass" name="Real" eSuperTypes="#//DataType/Normal"/>
    <eClassifiers xsi:type="ecore:EClass" name="RangeInt" eSuperTypes="#//DataType/Integer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minVal" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxVal" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Expressions" nsURI="file://C:/Users/martina/Desktop/eclipse_indigo/workspace/textToModelTrasformation/skipRulesExample/metamodels/mmAEmilia.ecore#//Expressions"
      nsPrefix="Expressions">
    <eClassifiers xsi:type="ecore:EClass" name="Expression"/>
    <eClassifiers xsi:type="ecore:EClass" name="ListExpr" eSuperTypes="#//Expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
          eType="#//Expressions/ListOpName"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="list_operands" upperBound="-1"
          eType="#//Expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArrayExpr" eSuperTypes="#//Expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
          eType="#//Expressions/ArrayOpName"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="array_operands" upperBound="-1"
          eType="#//Expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RecordExpr" eSuperTypes="#//Expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
          eType="#//Expressions/RecordOpName"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="record_operands" upperBound="-1"
          eType="#//Expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IdentExpr" eSuperTypes="#//Expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#//Expressions/IdentifierType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MathFunctions" eSuperTypes="#//Expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="#//Expressions/MathFuncName"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="leftExprMath" lowerBound="1"
          eType="#//Expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rightExprMath" eType="#//Expressions/Expression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RelationalExpr" eSuperTypes="#//Expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
          eType="#//Expressions/RelatOpName"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="leftExprRel" lowerBound="1"
          eType="#//Expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rightExprRel" lowerBound="1"
          eType="#//Expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArithExpr" eSuperTypes="#//Expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
          eType="#//Expressions/ArithOpName"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="leftExprArith" lowerBound="1"
          eType="#//Expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rightExprArith" lowerBound="1"
          eType="#//Expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pseudo_random_num_gen" eSuperTypes="#//Expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="#//Expressions/PseudoNumName"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="firstNumGenOp" lowerBound="1"
          eType="#//Expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="secondNumGenOp" eType="#//Expressions/Expression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="thirdNumGenOp" eType="#//Expressions/Expression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanExpr" eSuperTypes="#//Expressions/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
          eType="#//Expressions/BoolOpName"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="leftExprBool" eType="#//Expressions/Expression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rightExprBool" lowerBound="1"
          eType="#//Expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BoolOpName">
      <eLiterals name="NOT" literal="!"/>
      <eLiterals name="AND" value="1" literal="&amp;&amp;"/>
      <eLiterals name="OR" value="2" literal="||"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="MathFuncName">
      <eLiterals name="MOD" literal="mod"/>
      <eLiterals name="ABS" value="1" literal="abs"/>
      <eLiterals name="CEIL" value="2" literal="ceil"/>
      <eLiterals name="FLOOR" value="3" literal="floor"/>
      <eLiterals name="MIN" value="4" literal="min"/>
      <eLiterals name="MAX" value="5" literal="max"/>
      <eLiterals name="POWER" value="6" literal="power"/>
      <eLiterals name="EPOWER" value="7" literal="epower"/>
      <eLiterals name="LOGE" value="8" literal="loge"/>
      <eLiterals name="LOG10" value="9" literal="log10"/>
      <eLiterals name="SQRT" value="10" literal="sqrt"/>
      <eLiterals name="SIN" value="11" literal="sin"/>
      <eLiterals name="COS" value="12" literal="cos"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="RecordOpName">
      <eLiterals name="RECORD_CONS" literal="record_cons"/>
      <eLiterals name="GET" value="1" literal="get"/>
      <eLiterals name="PUT" value="2" literal="put"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="RelatOpName">
      <eLiterals name="GREATER" literal=">"/>
      <eLiterals name="GREATER_EQUAL" value="1" literal=">="/>
      <eLiterals name="LESS" value="2" literal="&lt;"/>
      <eLiterals name="LESS_EQUAL" value="3" literal="&lt;="/>
      <eLiterals name="EQUAL" value="4" literal="="/>
      <eLiterals name="NOT_EQUAL" value="5" literal="!="/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="IdentifierType">
      <eLiterals name="TYPED_IDENT"/>
      <eLiterals name="NUMERIC_CONST" value="1"/>
      <eLiterals name="TRUTH_VAL" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ArithOpName">
      <eLiterals name="PLUS" literal="+"/>
      <eLiterals name="MINUS" value="1" literal="-"/>
      <eLiterals name="DIV" value="2" literal="/"/>
      <eLiterals name="MULT" value="3" literal="*"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ArrayOpName">
      <eLiterals name="array_cons" literal="array_cons"/>
      <eLiterals name="read" value="1" literal="read"/>
      <eLiterals name="write" value="2" literal="write"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PseudoNumName">
      <eLiterals name="D_UNIFORM" literal="d_uniform"/>
      <eLiterals name="GAMMA" value="1" literal="gamma"/>
      <eLiterals name="C_UNIFORM" value="2" literal="c_uniform"/>
      <eLiterals name="ERLANG" value="3" literal="erlang"/>
      <eLiterals name="EXPONENTIAL" value="4" literal="exponential"/>
      <eLiterals name="WEIBULL" value="5" literal="weibull"/>
      <eLiterals name="BETA" value="6" literal="beta"/>
      <eLiterals name="NORMAL" value="7" literal="normal"/>
      <eLiterals name="PARETO" value="8" literal="pareto"/>
      <eLiterals name="B_PARETO" value="9" literal="b_pareto"/>
      <eLiterals name="BERNOULLI" value="10" literal="bernoulli"/>
      <eLiterals name="BINOMIAL" value="11" literal="binomial"/>
      <eLiterals name="POISSON" value="12" literal="poisson"/>
      <eLiterals name="NEG_BINOMIAL" value="13" literal="neg_binomial"/>
      <eLiterals name="GEOMETRIC" value="14" literal="geometric"/>
      <eLiterals name="PASCAL" value="15" literal="pascal"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ListOpName">
      <eLiterals name="LIST_CONS" literal="list_cons"/>
      <eLiterals name="FIRST" value="1" literal="first"/>
      <eLiterals name="TAIL" value="2" literal="tail"/>
      <eLiterals name="CONCAT" value="3" literal="concat"/>
      <eLiterals name="INSERT" value="4" literal="insert"/>
      <eLiterals name="REMOVE" value="5" literal="remove"/>
      <eLiterals name="LENGHT" value="6" literal="lenght"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Headers" nsURI="file://C:/Users/martina/Desktop/eclipse_indigo/workspace/textToModelTrasformation/skipRulesExample/metamodels/mmAEmilia.ecore#//Headers"
      nsPrefix="Headers">
    <eClassifiers xsi:type="ecore:EClass" name="AT_Header">
      <eStructuralFeatures xsi:type="ecore:EReference" name="initConst" upperBound="-1"
          eType="#//Headers/ConstInit" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConstInit">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initConstData" lowerBound="1"
          eType="#//DataType/DataType" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initConstExpr" lowerBound="1"
          eType="#//Expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ET_Header">
      <eStructuralFeatures xsi:type="ecore:EReference" name="costant" upperBound="-1"
          eType="#//Headers/Const" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Const">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constantData" lowerBound="1"
          eType="#//DataType/DataType" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BehavHeader">
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Headers/LeftSide"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Headers/RightSide"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LeftSide">
      <eStructuralFeatures xsi:type="ecore:EReference" name="initVar" upperBound="-1"
          eType="#//Headers/VarInit" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="varDef" upperBound="-1"
          eType="#//Headers/Var" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RightSide">
      <eStructuralFeatures xsi:type="ecore:EReference" name="localDef" upperBound="-1"
          eType="#//Headers/Local" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VarInit">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initVarExpr" lowerBound="1"
          eType="#//Expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initVarType" lowerBound="1"
          eType="#//DataType/Normal" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Var">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="varType" lowerBound="1"
          eType="#//DataType/Normal" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Local">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="localType" lowerBound="1"
          eType="#//DataType/Normal" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Behavior" nsURI="file://C:/Users/martina/Desktop/eclipse_indigo/workspace/textToModelTrasformation/skipRulesExample/metamodels/mmAEmilia.ecore#//Behavior"
      nsPrefix="Behavior">
    <eClassifiers xsi:type="ecore:EClass" name="Behavior">
      <eStructuralFeatures xsi:type="ecore:EReference" name="equations" upperBound="-1"
          eType="#//Behavior/BehavEquation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BehavEquation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bHeader" lowerBound="1"
          eType="#//Headers/BehavHeader" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pt" lowerBound="1" eType="#//Behavior/ProcessTerm"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProcessTerm">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Expressions/Expression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Stop" eSuperTypes="#//Behavior/ProcessTerm"/>
    <eClassifiers xsi:type="ecore:EClass" name="ChoiceProcess" eSuperTypes="#//Behavior/ProcessTerm">
      <eStructuralFeatures xsi:type="ecore:EReference" name="processes" upperBound="-1"
          eType="#//Behavior/ProcessTerm" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActionProcess" eSuperTypes="#//Behavior/ProcessTerm">
      <eStructuralFeatures xsi:type="ecore:EReference" name="process" lowerBound="1"
          eType="#//Behavior/ProcessTerm" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="act" lowerBound="1" eType="#//Behavior/Action"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BehavProcess" eSuperTypes="#//Behavior/ProcessTerm">
      <eStructuralFeatures xsi:type="ecore:EReference" name="eqCall" lowerBound="1"
          eType="#//Behavior/BehavEquation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exprs" eType="#//Expressions/Expression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Action">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="actThrought" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="actUtilization" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="actResponseTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="is" eType="#//Interaction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Behavior/ActionType"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rate" eType="#//Behavior/ActionRate"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActionType"/>
    <eClassifiers xsi:type="ecore:EClass" name="ActionInput" eSuperTypes="#//Behavior/ActionType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="var" lowerBound="1" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActionOutput" eSuperTypes="#//Behavior/ActionType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="exprOutput" upperBound="-1"
          eType="#//Expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActionRate"/>
    <eClassifiers xsi:type="ecore:EClass" name="RateExp" eSuperTypes="#//Behavior/ActionRate">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1"
          eType="#//Expressions/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RateInf" eSuperTypes="#//Behavior/ActionRate">
      <eStructuralFeatures xsi:type="ecore:EReference" name="inf_priority" eType="#//Expressions/Expression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inf_weight" eType="#//Expressions/Expression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Rate_" eSuperTypes="#//Behavior/ActionRate">
      <eStructuralFeatures xsi:type="ecore:EReference" name="priority" eType="#//Expressions/Expression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="weight" eType="#//Expressions/Expression"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
