<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="StrutsMM" nsURI="gts.inf.um.es/Struts" nsPrefix="strutsmm">
    <eSubpackages name="StrutsConfigMM" nsURI="gts.inf.um.es/Struts/Struts-config"
        nsPrefix="strutscmm">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="qualified" value="false"/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EClass" name="ActionMappingsType">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="action-mappings_._type"/>
          <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="action" upperBound="-1"
            eType="#/0/StrutsConfigMM/ActionType" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="action"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
            iD="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="id"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#/0/StrutsConfigMM/ClassName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="type"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ActionType">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="action_._type"/>
          <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="icon" eType="#/0/StrutsConfigMM/IconType"
            containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="icon"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="displayName" eType="#/0/StrutsConfigMM/DisplayNameType"
            containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="display-name"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="#/0/StrutsConfigMM/DescriptionType"
            containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="description"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="setProperty" upperBound="-1"
            eType="#/0/StrutsConfigMM/SetPropertyType" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="set-property"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="exception" upperBound="-1"
            eType="#/0/StrutsConfigMM/ExceptionType" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="exception"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="forward" upperBound="-1"
            eType="#/0/StrutsConfigMM/ForwardType" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="forward"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" eType="#/0/StrutsConfigMM/BeanName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="attribute"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="#/0/StrutsConfigMM/ClassName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="className"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="forward1" eType="#/0/StrutsConfigMM/RequestPath">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="forward"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
            iD="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="id"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="include" eType="#/0/StrutsConfigMM/RequestPath">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="include"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="input" eType="#/0/StrutsConfigMM/RequestPath">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="input"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#/0/StrutsConfigMM/BeanName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="name"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameter" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="parameter"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1"
            eType="#/0/StrutsConfigMM/RequestPath">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="path"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="prefix"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="roles" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="roles"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="scope" eType="#/0/StrutsConfigMM/RequestScope"
            defaultValueLiteral="request" unsettable="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="scope"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="suffix" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="suffix"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#/0/StrutsConfigMM/ClassName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="type"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="unknown" eType="#/0/StrutsConfigMM/Boolean"
            defaultValueLiteral="true" unsettable="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="unknown"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="validate" eType="#/0/StrutsConfigMM/Boolean"
            defaultValueLiteral="true" unsettable="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="validate"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="javaClass" lowerBound="1"
            eType="#/0/StrutsBeansMM/StrutsJavaClass"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EDataType" name="AttributeName" instanceClassName="java.lang.String">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="AttributeName"/>
          <details key="baseType" value="http://www.eclipse.org/emf/2003/XMLType#string"/>
        </eAnnotations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EDataType" name="BeanName" instanceClassName="java.lang.String">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="BeanName"/>
          <details key="baseType" value="http://www.eclipse.org/emf/2003/XMLType#string"/>
        </eAnnotations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="Boolean">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="Boolean"/>
        </eAnnotations>
        <eLiterals name="true"/>
        <eLiterals name="false" value="1"/>
        <eLiterals name="yes" value="2"/>
        <eLiterals name="no" value="3"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EDataType" name="BooleanObject" instanceClassName="org.eclipse.emf.common.util.Enumerator">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="Boolean:Object"/>
          <details key="baseType" value="Boolean"/>
        </eAnnotations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EDataType" name="ClassName" instanceClassName="java.lang.String">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="ClassName"/>
          <details key="baseType" value="http://www.eclipse.org/emf/2003/XMLType#string"/>
        </eAnnotations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ControllerType">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="controller_._type"/>
          <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="setProperty" upperBound="-1"
            eType="#/0/StrutsConfigMM/SetPropertyType" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="set-property"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="bufferSize" eType="#/0/StrutsConfigMM/Integer">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="bufferSize"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="#/0/StrutsConfigMM/ClassName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="className"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentType" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="contentType"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="debug" eType="#/0/StrutsConfigMM/Integer">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="debug"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="forwardPattern" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="forwardPattern"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
            iD="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="id"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputForward" eType="#/0/StrutsConfigMM/Boolean"
            defaultValueLiteral="true" unsettable="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="inputForward"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="locale" eType="#/0/StrutsConfigMM/Boolean"
            defaultValueLiteral="true" unsettable="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="locale"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxFileSize" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="maxFileSize"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="memFileSize" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="memFileSize"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="multipartClass" eType="#/0/StrutsConfigMM/ClassName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="multipartClass"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="nocache" eType="#/0/StrutsConfigMM/Boolean"
            defaultValueLiteral="true" unsettable="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="nocache"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="pagePattern" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="pagePattern"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="processorClass" eType="#/0/StrutsConfigMM/ClassName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="processorClass"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="tempDir" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="tempDir"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DataSourcesType">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="data-sources_._type"/>
          <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="dataSource" upperBound="-1"
            eType="#/0/StrutsConfigMM/DataSourceType" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="data-source"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
            iD="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="id"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DataSourceType">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="data-source_._type"/>
          <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="setProperty" upperBound="-1"
            eType="#/0/StrutsConfigMM/SetPropertyType" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="set-property"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="#/0/StrutsConfigMM/ClassName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="className"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
            iD="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="id"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="#/0/StrutsConfigMM/AttributeName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="key"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#/0/StrutsConfigMM/ClassName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="type"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DescriptionType">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="description_._type"/>
          <details key="kind" value="mixed"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="mixed" unique="false"
            upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="elementWildcard"/>
            <details key="name" value=":mixed"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
            iD="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="id"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DisplayNameType">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="display-name_._type"/>
          <details key="kind" value="mixed"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="mixed" unique="false"
            upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="elementWildcard"/>
            <details key="name" value=":mixed"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
            iD="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="id"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DocumentRoot">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value=""/>
          <details key="kind" value="mixed"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="mixed" unique="false"
            upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="elementWildcard"/>
            <details key="name" value=":mixed"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="xMLNSPrefixMap" upperBound="-1"
            eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStringToStringMapEntry"
            transient="true" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="xmlns:prefix"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="xSISchemaLocation"
            upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStringToStringMapEntry"
            transient="true" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="xsi:schemaLocation"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="action" upperBound="-2"
            eType="#/0/StrutsConfigMM/ActionType" volatile="true" transient="true"
            derived="true" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="action"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="actionMappings" upperBound="-2"
            eType="#/0/StrutsConfigMM/ActionMappingsType" volatile="true" transient="true"
            derived="true" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="action-mappings"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="controller" upperBound="-2"
            eType="#/0/StrutsConfigMM/ControllerType" volatile="true" transient="true"
            derived="true" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="controller"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="dataSource" upperBound="-2"
            eType="#/0/StrutsConfigMM/DataSourceType" volatile="true" transient="true"
            derived="true" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="data-source"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="dataSources" upperBound="-2"
            eType="#/0/StrutsConfigMM/DataSourcesType" volatile="true" transient="true"
            derived="true" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="data-sources"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="description" upperBound="-2"
            eType="#/0/StrutsConfigMM/DescriptionType" volatile="true" transient="true"
            derived="true" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="description"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="displayName" upperBound="-2"
            eType="#/0/StrutsConfigMM/DisplayNameType" volatile="true" transient="true"
            derived="true" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="display-name"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="exception" upperBound="-2"
            eType="#/0/StrutsConfigMM/ExceptionType" volatile="true" transient="true"
            derived="true" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="exception"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="formBean" upperBound="-2"
            eType="#/0/StrutsConfigMM/FormBeanType" volatile="true" transient="true"
            derived="true" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="form-bean"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="formBeans" upperBound="-2"
            eType="#/0/StrutsConfigMM/FormBeansType" volatile="true" transient="true"
            derived="true" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="form-beans"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="formProperty" upperBound="-2"
            eType="#/0/StrutsConfigMM/FormPropertyType" volatile="true" transient="true"
            derived="true" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="form-property"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="forward" upperBound="-2"
            eType="#/0/StrutsConfigMM/ForwardType" volatile="true" transient="true"
            derived="true" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="forward"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="globalExceptions" upperBound="-2"
            eType="#/0/StrutsConfigMM/GlobalExceptionsType" volatile="true" transient="true"
            derived="true" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="global-exceptions"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="globalForwards" upperBound="-2"
            eType="#/0/StrutsConfigMM/GlobalForwardsType" volatile="true" transient="true"
            derived="true" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="global-forwards"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="icon" upperBound="-2"
            eType="#/0/StrutsConfigMM/IconType" volatile="true" transient="true" derived="true"
            containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="icon"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="largeIcon" upperBound="-2"
            eType="#/0/StrutsConfigMM/LargeIconType" volatile="true" transient="true"
            derived="true" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="large-icon"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="messageResources" upperBound="-2"
            eType="#/0/StrutsConfigMM/MessageResourcesType" volatile="true" transient="true"
            derived="true" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="message-resources"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="plugIn" upperBound="-2"
            eType="#/0/StrutsConfigMM/PlugInType" volatile="true" transient="true"
            derived="true" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="plug-in"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="setProperty" upperBound="-2"
            eType="#/0/StrutsConfigMM/SetPropertyType" volatile="true" transient="true"
            derived="true" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="set-property"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="smallIcon" upperBound="-2"
            eType="#/0/StrutsConfigMM/SmallIconType" volatile="true" transient="true"
            derived="true" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="small-icon"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="strutsConfig" upperBound="-2"
            eType="#/0/StrutsConfigMM/StrutsConfigType" volatile="true" transient="true"
            derived="true" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="struts-config"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ExceptionType">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="exception_._type"/>
          <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="icon" eType="#/0/StrutsConfigMM/IconType"
            containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="icon"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="displayName" eType="#/0/StrutsConfigMM/DisplayNameType"
            containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="display-name"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="#/0/StrutsConfigMM/DescriptionType"
            containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="description"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="setProperty" upperBound="-1"
            eType="#/0/StrutsConfigMM/SetPropertyType" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="set-property"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="bundle" eType="#/0/StrutsConfigMM/AttributeName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="bundle"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="#/0/StrutsConfigMM/ClassName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="className"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="handler" eType="#/0/StrutsConfigMM/ClassName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="handler"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
            iD="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="id"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="key"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="#/0/StrutsConfigMM/RequestPath">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="path"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="scope" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="scope"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
            eType="#/0/StrutsConfigMM/ClassName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="type"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FormBeansType">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="form-beans_._type"/>
          <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="formBean" upperBound="-1"
            eType="#/0/StrutsConfigMM/FormBeanType" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="form-bean"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
            iD="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="id"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#/0/StrutsConfigMM/ClassName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="type"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FormBeanType">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="form-bean_._type"/>
          <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="icon" eType="#/0/StrutsConfigMM/IconType"
            containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="icon"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="displayName" eType="#/0/StrutsConfigMM/DisplayNameType"
            containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="display-name"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="#/0/StrutsConfigMM/DescriptionType"
            containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="description"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="setProperty" upperBound="-1"
            eType="#/0/StrutsConfigMM/SetPropertyType" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="set-property"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="formProperty" upperBound="-1"
            eType="#/0/StrutsConfigMM/FormPropertyType" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="form-property"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="#/0/StrutsConfigMM/ClassName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="className"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="dynamic" eType="#/0/StrutsConfigMM/Boolean"
            defaultValueLiteral="true" unsettable="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="dynamic"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
            iD="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="id"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
            eType="#/0/StrutsConfigMM/BeanName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="name"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
            eType="#/0/StrutsConfigMM/ClassName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="type"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="javaClass" lowerBound="1"
            eType="#/0/StrutsBeansMM/StrutsJavaClass"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FormPropertyType">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="form-property_._type"/>
          <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="setProperty" upperBound="-1"
            eType="#/0/StrutsConfigMM/SetPropertyType" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="set-property"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="#/0/StrutsConfigMM/ClassName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="className"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="initial" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="initial"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
            eType="#/0/StrutsConfigMM/PropName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="name"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="#/0/StrutsConfigMM/Integer">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="size"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
            eType="#/0/StrutsConfigMM/ClassName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="type"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ForwardType">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="forward_._type"/>
          <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="icon" eType="#/0/StrutsConfigMM/IconType"
            containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="icon"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="displayName" eType="#/0/StrutsConfigMM/DisplayNameType"
            containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="display-name"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="#/0/StrutsConfigMM/DescriptionType"
            containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="description"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="setProperty" upperBound="-1"
            eType="#/0/StrutsConfigMM/SetPropertyType" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="set-property"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="#/0/StrutsConfigMM/ClassName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="className"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="contextRelative" eType="#/0/StrutsConfigMM/Boolean"
            defaultValueLiteral="true" unsettable="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="contextRelative"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
            iD="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="id"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="name"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1"
            eType="#/0/StrutsConfigMM/RequestPath">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="path"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="redirect" eType="#/0/StrutsConfigMM/Boolean"
            defaultValueLiteral="true" unsettable="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="redirect"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="GlobalExceptionsType">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="global-exceptions_._type"/>
          <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="exception" upperBound="-1"
            eType="#/0/StrutsConfigMM/ExceptionType" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="exception"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
            iD="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="id"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="GlobalForwardsType">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="global-forwards_._type"/>
          <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="forward" upperBound="-1"
            eType="#/0/StrutsConfigMM/ForwardType" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="forward"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
            iD="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="id"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#/0/StrutsConfigMM/ClassName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="type"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="IconType">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="icon_._type"/>
          <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="smallIcon" eType="#/0/StrutsConfigMM/SmallIconType"
            containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="small-icon"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="largeIcon" eType="#/0/StrutsConfigMM/LargeIconType"
            containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="large-icon"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
            iD="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="id"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceClassName="java.lang.String">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="Integer"/>
          <details key="baseType" value="http://www.eclipse.org/emf/2003/XMLType#string"/>
        </eAnnotations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="LargeIconType">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="large-icon_._type"/>
          <details key="kind" value="mixed"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="mixed" unique="false"
            upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="elementWildcard"/>
            <details key="name" value=":mixed"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
            iD="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="id"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="MessageResourcesType">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="message-resources_._type"/>
          <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="setProperty" upperBound="-1"
            eType="#/0/StrutsConfigMM/SetPropertyType" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="set-property"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="#/0/StrutsConfigMM/ClassName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="className"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="factory" eType="#/0/StrutsConfigMM/ClassName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="factory"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
            iD="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="id"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="#/0/StrutsConfigMM/AttributeName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="key"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="null" eType="#/0/StrutsConfigMM/Boolean"
            defaultValueLiteral="true" unsettable="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="null"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameter" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="parameter"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PlugInType">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="plug-in_._type"/>
          <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="setProperty" upperBound="-1"
            eType="#/0/StrutsConfigMM/SetPropertyType" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="set-property"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" lowerBound="1"
            eType="#/0/StrutsConfigMM/ClassName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="className"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
            iD="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="id"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EDataType" name="PropName" instanceClassName="java.lang.String">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="PropName"/>
          <details key="baseType" value="http://www.eclipse.org/emf/2003/XMLType#string"/>
        </eAnnotations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EDataType" name="RequestPath" instanceClassName="java.lang.String">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="RequestPath"/>
          <details key="baseType" value="http://www.eclipse.org/emf/2003/XMLType#string"/>
        </eAnnotations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="RequestScope">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="RequestScope"/>
        </eAnnotations>
        <eLiterals name="request"/>
        <eLiterals name="session" value="1"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EDataType" name="RequestScopeObject" instanceClassName="org.eclipse.emf.common.util.Enumerator">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="RequestScope:Object"/>
          <details key="baseType" value="RequestScope"/>
        </eAnnotations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SetPropertyType">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="set-property_._type"/>
          <details key="kind" value="empty"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
            iD="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="id"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="property" lowerBound="1"
            eType="#/0/StrutsConfigMM/PropName">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="property"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//AnySimpleType">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="value"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SmallIconType">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="small-icon_._type"/>
          <details key="kind" value="mixed"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="mixed" unique="false"
            upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFeatureMapEntry">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="elementWildcard"/>
            <details key="name" value=":mixed"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
            iD="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="id"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StrutsConfigType">
        <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
          <details key="name" value="struts-config_._type"/>
          <details key="kind" value="elementOnly"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="dataSources" eType="#/0/StrutsConfigMM/DataSourcesType"
            containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="data-sources"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="formBeans" eType="#/0/StrutsConfigMM/FormBeansType"
            containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="form-beans"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="globalExceptions" eType="#/0/StrutsConfigMM/GlobalExceptionsType"
            containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="global-exceptions"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="globalForwards" eType="#/0/StrutsConfigMM/GlobalForwardsType"
            containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="global-forwards"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="actionMappings" eType="#/0/StrutsConfigMM/ActionMappingsType"
            containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="action-mappings"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="controller" eType="#/0/StrutsConfigMM/ControllerType"
            containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="controller"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="messageResources" upperBound="-1"
            eType="#/0/StrutsConfigMM/MessageResourcesType" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="message-resources"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="plugIn" upperBound="-1"
            eType="#/0/StrutsConfigMM/PlugInType" containment="true" resolveProxies="false">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="element"/>
            <details key="name" value="plug-in"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
            iD="true">
          <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
            <details key="kind" value="attribute"/>
            <details key="name" value="id"/>
            <details key="namespace" value="##targetNamespace"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="StrutsBeansMM" nsURI="gts.inf.um.es/Struts/Struts-beans" nsPrefix="strutsbmm">
      <eClassifiers xsi:type="ecore:EEnum" name="StrutsClassType">
        <eLiterals name="ACTION"/>
        <eLiterals name="ACTION_FORM" value="1"/>
        <eLiterals name="NORMAL_JAVA_CLASS" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StrutsBeans">
        <eStructuralFeatures xsi:type="ecore:EReference" name="beans" upperBound="-1"
            eType="#/0/StrutsBeansMM/StrutsJavaClass" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
            eType="#/1/Type" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="beanMappings" upperBound="-1"
            eType="#/0/StrutsBeansMM/BeanMapping" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StrutsJavaClass" eSuperTypes="#/1/JavaClass">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="strutsClassType" lowerBound="1"
            eType="#/0/StrutsBeansMM/StrutsClassType"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="containerBeanMapping"
            lowerBound="1" eType="#/0/StrutsBeansMM/BeanMapping"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ValidateMethod" eSuperTypes="#/1/Method">
        <eStructuralFeatures xsi:type="ecore:EReference" name="actionMappingParameter"
            lowerBound="1" eType="#/1/Parameter"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="requestParameter" lowerBound="1"
            eType="#/1/Parameter"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="actionErrorsVar" lowerBound="1"
            eType="#/1/Name" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="containerBean" lowerBound="1"
            eType="#/0/StrutsBeansMM/StrutsJavaClass"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ExecuteMethod" eSuperTypes="#/1/Method">
        <eStructuralFeatures xsi:type="ecore:EReference" name="actionMappingParameter"
            lowerBound="1" eType="#/1/Parameter"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="actionFormParameter"
            lowerBound="1" eType="#/1/Parameter"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="requestParameter" lowerBound="1"
            eType="#/1/Parameter"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="responseParameter"
            lowerBound="1" eType="#/1/Parameter"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="containerBean" lowerBound="1"
            eType="#/0/StrutsBeansMM/StrutsJavaClass"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BeanMapping">
        <eStructuralFeatures xsi:type="ecore:EReference" name="actionFormBean" lowerBound="1"
            eType="#/0/StrutsBeansMM/StrutsJavaClass"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="actionBeans" upperBound="-1"
            eType="#/0/StrutsBeansMM/StrutsJavaClass"/>
      </eClassifiers>
    </eSubpackages>
  </ecore:EPackage>
  <ecore:EPackage name="JavaSimplified" nsURI="gts.inf.um.es/javaSimplified" nsPrefix="javas">
    <eClassifiers xsi:type="ecore:EClass" name="StringElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="strValue" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="name" lowerBound="1"
          eType="#/1/Name" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#/1/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Type">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Comment" eSuperTypes="#/1/StringElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isJavadoc" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CommentedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="comment" eType="#/1/Comment"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="InfixOperatorType">
      <eLiterals name="EQUALS"/>
      <eLiterals name="NOT_EQUALS" value="1"/>
      <eLiterals name="CONDITIONAL_AND" value="2" literal="CONDITIONAL_AND"/>
      <eLiterals name="CONDITIONAL_OR" value="3" literal="CONDITIONAL_OR"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="AssignmentOperatorType">
      <eLiterals name="ASSIGN"/>
      <eLiterals name="PLUS_ASSIGN" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="LiteralType">
      <eLiterals name="STRING"/>
      <eLiterals name="INTEGER" value="1"/>
      <eLiterals name="BOOLEAN" value="2"/>
      <eLiterals name="NULL" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="VisibilityType">
      <eLiterals name="PUBLIC"/>
      <eLiterals name="PROTECTED" value="1"/>
      <eLiterals name="PACKAGE" value="2"/>
      <eLiterals name="PRIVATE" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#/1/CommentedElement #/1/NamedElement #/1/StringElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" lowerBound="1"
          eType="#/1/VisibilityType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JavaClass" abstract="true" eSuperTypes="#/1/CommentedElement #/1/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="imports" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
          eType="#/1/Field" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
          eType="#/1/Method" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Field" eSuperTypes="#/1/TypedElement #/1/Feature">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#/1/Expression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#/1/Feature">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#/1/Parameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="exceptions" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
          eType="#/1/Statement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#/1/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#/1/NamedElement #/1/TypedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Statement" eSuperTypes="#/1/StringElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="CommentStatement" eSuperTypes="#/1/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="comment" lowerBound="1"
          eType="#/1/Comment" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExpressionStatement" eSuperTypes="#/1/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1"
          eType="#/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IfStatement" eSuperTypes="#/1/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1"
          eType="#/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ifst" lowerBound="1"
          upperBound="-1" eType="#/1/Statement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elsest" upperBound="-1"
          eType="#/1/Statement" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VariableDeclarationStatement" eSuperTypes="#/1/Statement #/1/TypedElement #/1/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="#/1/Expression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReturnStatement" eSuperTypes="#/1/Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1"
          eType="#/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="#/1/StringElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="Name" eSuperTypes="#/1/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CastExpression" eSuperTypes="#/1/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1"
          eType="#/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#/1/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MethodInvocation" eSuperTypes="#/1/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="#/1/Name"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="method" lowerBound="1"
          eType="#/1/MethodCall" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MethodCall">
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
          eType="#/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="childCall" upperBound="-1"
          eType="#/1/MethodCall" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="methodName" lowerBound="1"
          eType="#/1/Name" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InfixExpression" eSuperTypes="#/1/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expr1" lowerBound="1"
          eType="#/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
          eType="#/1/InfixOperatorType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expr2" lowerBound="1"
          eType="#/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="#/1/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expr1" lowerBound="1"
          eType="#/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
          eType="#/1/AssignmentOperatorType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expr2" lowerBound="1"
          eType="#/1/Expression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Literal" eSuperTypes="#/1/Expression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="#/1/LiteralType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ClassInstanceCreation" eSuperTypes="#/1/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
          eType="#/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="className" lowerBound="1"
          eType="#/1/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ThisExpression" eSuperTypes="#/1/Expression"/>
    <eClassifiers xsi:type="ecore:EClass" name="FieldAccess" eSuperTypes="#/1/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1"
          eType="#/1/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="name" lowerBound="1"
          eType="#/1/Name" containment="true"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
